### ISSUE TITLE
about fmincon stopped  ?  matlab2021a , but code can run

### ISSUE THREAD

**Issue by bao666liang** [ACIPL/MPC4AMVs#1]
Solver stopped prematurely.

fmincon stopped because it exceeded the function evaluation limit,
options.MaxFunctionEvaluations = 1.200000e+03.

Local minimum possible. Constraints satisfied.

fmincon stopped because the size of the current step is less than
the value of the step size tolerance and constraints are 
satisfied to within the value of the constraint tolerance.

<stopping criteria details>

![image](https://user-images.githubusercontent.com/91942808/202965649-6373629c-9f71-4f50-973d-78a794118541.png)

**Comment by Vincent-swt** [comment]
I also had a similar problem. How was it solved？
